version: '3.7'
services:

  wechat-bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: wechat-bot
#    restart: always
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./src/:/app/src/
#      - ./node_modules/:/app/node_modules/
#      - ./package-lock.json:/app/package-lock.json
    depends_on:
      - redis
    entrypoint: ['sh','./entrypoint.sh']
    command:
      - sh
      - -c
      - |
        npm run dev

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      # Mount the redis data directory to the container.
      - ./volumes/redis/data:/data
    # Set the redis password when startup redis server.
    command: redis-server --requirepass 123456
    ports:
      - 6666:6379
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]